<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Rotas extends \Application\Entity\Rotas implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'data', 'cidorigem', 'ciddestino', 'hrsaida', 'hrchegada', 'kminicial', 'kmfinal', 'distancia', 'tempo', 'obs');
        }

        return array('__isInitialized__', 'id', 'data', 'cidorigem', 'ciddestino', 'hrsaida', 'hrchegada', 'kminicial', 'kmfinal', 'distancia', 'tempo', 'obs');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Rotas $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', array());

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function setData($data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setData', array($data));

        return parent::setData($data);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidorigem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidorigem', array());

        return parent::getCidorigem();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidorigem($cidorigem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidorigem', array($cidorigem));

        return parent::setCidorigem($cidorigem);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiddestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiddestino', array());

        return parent::getCiddestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiddestino($ciddestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiddestino', array($ciddestino));

        return parent::setCiddestino($ciddestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrsaida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrsaida', array());

        return parent::getHrsaida();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrsaida($hrsaida)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrsaida', array($hrsaida));

        return parent::setHrsaida($hrsaida);
    }

    /**
     * {@inheritDoc}
     */
    public function getHrchegada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHrchegada', array());

        return parent::getHrchegada();
    }

    /**
     * {@inheritDoc}
     */
    public function setHrchegada($hrchegada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHrchegada', array($hrchegada));

        return parent::setHrchegada($hrchegada);
    }

    /**
     * {@inheritDoc}
     */
    public function getKminicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKminicial', array());

        return parent::getKminicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setKminicial($kminicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKminicial', array($kminicial));

        return parent::setKminicial($kminicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getKmfinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKmfinal', array());

        return parent::getKmfinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setKmfinal($kmfinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKmfinal', array($kmfinal));

        return parent::setKmfinal($kmfinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDistancia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDistancia', array());

        return parent::getDistancia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDistancia($distancia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDistancia', array($distancia));

        return parent::setDistancia($distancia);
    }

    /**
     * {@inheritDoc}
     */
    public function getTempo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTempo', array());

        return parent::getTempo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTempo($tempo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTempo', array($tempo));

        return parent::setTempo($tempo);
    }

    /**
     * {@inheritDoc}
     */
    public function getObs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObs', array());

        return parent::getObs();
    }

    /**
     * {@inheritDoc}
     */
    public function setObs($obs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObs', array($obs));

        return parent::setObs($obs);
    }

}
