<div class="container">
	<h3>Users</h3>
	<p><a href="<?php echo $this->url('sonuser-admin/default', array('action' =>'new')); ?>" class="btn btn-primary">Novo Usuário</a></p>
	<!--
	Isso: $this->url('sonuser-admin/default', array('action' =>'new'));
	equivale a  isso: /admin/users/nev
	-->

	<div class="table-responsive">
		<table class="table table-striped">
			<tr>
				<th>ID</th>
				<th>Nome</th>
				<th>Email</th>
				<th>Ação</th>
			</tr>

			<?php  foreach ($this->data as $entity): ?>
			<tr>
					<td><?php  echo $entity->getId(); ?></td>
					<td><?php  echo $entity->getNome(); ?></td>
					<td><?php  echo $entity->getEmail(); ?></td>
					<td>
						<a href="<?php echo $this->url('sonuser-admin/default',
									array('controller' => 'users','action' => 'edit', 'id' =>$entity->getId())); ?>" >Editar</a>
						<a href="<?php echo $this->url('sonuser-admin/default',
									array('controller' => 'users','action' => 'delete', 'id' =>$entity->getId())); ?>" >Delete</a>
					</td>
			</tr>
			<?php endforeach; ?>
		</table>
		<br />
	</div>
	<?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>
</div>