<!doctype html>
<html ng-app="myApp">
<head>
    <meta charset="UTF-8" />
    <title>Controle Pessoal</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="css/bootstrap_221.min.css" media="screen" rel="stylesheet" type="text/css" />

    <!-- <link href="css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" /> -->
    <!-- <link href="css/estilo.css" media="screen" rel="stylesheet" type="text/css" /> -->
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Controle Pessoal</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                          <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastro <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/trampo">Trampo</a></li>
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/pecas">Peças</a></li>
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/veiculo">Veículo</a></li>
                          </ul>
                        </li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Consulta <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="#/trampo/listarPorData">por Data</a></li>
                            <li><a href="#">por Mês</a></li>
                            <li><a href="#/trampo/listarPorTecnologia">por Tecnologia</a></li>
                          </ul>
                        </li>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Imprimir <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="/producaomes">Produção MES</a></li>
                          </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

            <?=$this->content;?>

            <footer>
                <div class="col-md-12 text-center">
                    <div class="well well-sm">
                        <div class="col-md-2">Controle Pessoal</div>
                        <div class="col-md-10 text-right">
                            Developed by <a href="http://www.luxu.com.br" target="_blank">Luciano Martins</a>
                            <?php echo date('Y') ?>
                        </div>
                    </div>
                </div>
            </footer>

</body>
</html>