<!doctype html>
<html ng-app="myApp">
<head>
    <meta charset="UTF-8" />
    <title>Controle Pessoal</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css" />
    <link href="css/estilo.css" media="screen" rel="stylesheet" type="text/css" />
</head>
<body>
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Controle Pessoal</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cadastro <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/trampo">Trampo</a></li>
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/pecas">Peças</a></li>
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/veiculo">Veículo</a></li>
                            <li><a data-toggle="collapse" data-target=".navbar-collapse" href="#/rotas">Rotas</a></li>
                          </ul>
                        </li>
                        <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Consulta <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="#/trampo/listarPorData">por Data</a></li>
                            <li><a href="#">por Mês</a></li>
                            <li><a href="#/trampo/listarPorTecnologia">por Tecnologia</a></li>
                          </ul>
                        </li>
                        <li class="dropdown">
                          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Imprimir <span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="/producaomes">Produção MES</a></li>
                            <li><a href="/api/pecas">Carregar peças</a></li>
                          </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
        <?=$this->content;?>
        <footer>
            <div class="col-md-12 text-center">
                <div class="well well-sm">
                    <div class="col-md-2">Controle Pessoal</div>
                    <div class="col-md-10 text-right">
                        Developed by <a href="http://www.luxu.com.br" target="_blank">Luciano Martins</a>
                        <?php echo date('Y') ?>
                    </div>
                </div>
            </div>
        </footer>

 <!-- AngularJS v1.6.1 2010-2016 Google, Inc. http://angularjs.org -->
<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script> -->
<script src="js/jquery-1.12.4.min.js"></script>
<script src="js/angular.min.js"></script>
<script src="js/angular-route.min.js"></script>
<script src="js/angular-resource.min.js"></script>
<script src="js/angular-animate.min.js"></script>
<script src="js/angular-touch.min.js"></script>
<script src="js/angular-locale_pt-br.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/dirPagination.js"></script>
<script src="js/checklist-model.min.js"></script>
<!-- <script src="js/kendo.all.min.js"></script> -->
<script src="js/bootstrap3-typeahead.min.js"></script>
<script src="https://rawgit.com/aguirrel/ng-currency/latest/dist/ng-currency.js"></script>

<script src="projetoangular/app.js"></script>
<script src="projetoangular/veiculoController.js"></script>
<script src="projetoangular/pecasController.js"></script>
<script src="projetoangular/trampoController.js"></script>
<script src="projetoangular/itensPecasController.js"></script>
<script src="projetoangular/rotasController.js"></script>
<script src="projetoangular/loginController.js"></script>

</body>
</html>